version: '3.0'
services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./src:/usr/local/apache2/htdocs/