apiVersion: v1
kind: Secret
metadata:
  name: space-docker-registry
  namespace: {{ .Release.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
