name: Build and Deploy Docker Image

on:
  push:
    branches: [ 'develop', 'production' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Image Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_PRIVATE_REGISTRY }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - name: Create registry path
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: .docker/Dockerfile
          tags: ${{ vars.DOCKER_PRIVATE_REGISTRY }}/${{ env.REPO }}/app:${{ github.ref_name }}
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: azure/setup-helm@v3
        with:
          version: '3.10.3'
        name: Setup Helm
      - name: Create Variables for Release
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
          echo "KUBE_NAMESPACE=$(echo $(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]') | tr '/' '-')-$GITHUB_REF_NAME" >> ${GITHUB_ENV}
      - name: Prepare Ingress Host Variable
        run: |
          if [ "$GITHUB_REF_NAME" == "production" ]; then
            echo "INGRESS_HOST=${{ vars.INGRESS_DOMAIN }}" >> ${GITHUB_ENV}
          else
            echo "INGRESS_HOST=$GITHUB_REF_NAME.${{ vars.INGRESS_DOMAIN }}" >> ${GITHUB_ENV}
          fi
      - name: Upgrade Release (Helm)
        run: |
          helm upgrade ${{ github.ref_name }} .helm \
            --install \
            --namespace ${{ env.KUBE_NAMESPACE }} \
            --create-namespace \
            --set-string image.url="${{ vars.DOCKER_PRIVATE_REGISTRY }}/${{ env.REPO }}/app:${{ github.ref_name }} \
            --set-string imageCredentials.password="${{ secrets.MAVEN_PASSWORD }}" \
            --set-string imageCredentials.username="${{ secrets.MAVEN_USERNAME }}" \
            --set-string imageCredentials.registry="${{ vars.DOCKER_PRIVATE_REGISTRY }}" \
            -f ${{ vars.HELM_VALUES }}
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"