name: Build and Deploy Docker Image

on:
  push:
    branches: [ 'develop', 'production' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Image Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_PRIVATE_REGISTRY }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - name: Create registry path
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: .docker/Dockerfile
          tags: ${{ env.REPO }}/app:${{ github.ref_name }}